### PR TITLE
Added DevOpsDays-Austin pictures

### PR DESCRIPTION
**Pull request by gallimorej**
I'm going to add a page to the DevOpsDays DC wiki with descriptions for these photos. Should provide a useful reference for our activities.

### CODE REVIEW

**Comment by gallimorej** [comment]
BTW, this is my first pull request on GitHub (!) so if I effed something up, feel free to kill this - and then kill me.

**Comment by nathenharvey** [comment]
@gallimorej the PR looks OK but we actually want to add these to the wiki which is in a different repository:  https://github.com/DevOpsDaysDC/planning.wiki.git

I can move them over, if you like, or you can clone that repo, add them them and then push them up.

**Comment by owdd** [comment]
The DevOps Days Austin badge is pretty awesome looking!  I'm definitely curious to hear about your experience there.

**Comment by gallimorej** [comment]
I'm trying to push but getting "Permission Denied".

ERROR: Permission to DevOpsDaysDC/planning.wiki.git denied to gallimorej.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I know you're not the GitHub help desk... Simple permission issue or config on my side?

**Comment by nathenharvey** [comment]
@gallimorej I invited you as an owner to the org.  accept the invite and try pushing again?

**Comment by gallimorej** [comment]
That worked. All good.

**Pull request closed without merging**
